<?php

namespace CentralCondo\Repositories\Portal\Condominium\Unit;

use Prettus\Repository\Eloquent\BaseRepository;
use Prettus\Repository\Criteria\RequestCriteria;
use CentralCondo\Repositories\Portal\Condominium\Unit\UnitRepository;
use CentralCondo\Entities\Portal\Condominium\Unit\Unit;
use CentralCondo\Validators\Portal\Condominium\Unit\UnitValidator;

/**
 * Class UnitRepositoryEloquent
 * @package namespace CentralCondo\Repositories\Portal;
 */
class UnitRepositoryEloquent extends BaseRepository implements UnitRepository
{

    public function listUnit(){
        return $this->model->lists('name', 'id');
    }

    public function presenter()
    {
        return parent::presenter(); // TODO: Change the autogenerated stub]
        //return "Prettus\\Repository\\Presenter\\ModelFractalPresenter";
    }

    /**
     * Specify Model class name
     *
     * @return string
     */
    public function model()
    {
        return Unit::class;
    }

    /**
    * Specify Validator class name
    *
    * @return mixed
    */
    public function validator()
    {
        return UnitValidator::class;
    }

    /**
     * Boot up the repository, pushing criteria
     */
    public function boot()
    {
        $this->pushCriteria(app(RequestCriteria::class));
    }

}
